# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_management.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66ile_management.proto\x12\x0e\x66ilemanagement\"\x1c\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"0\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x96\x01\n\x0b\x46ileManager\x12\x42\n\x06Upload\x12\x18.filemanagement.FileInfo\x1a\x1c.filemanagement.FileResponse\"\x00\x12\x43\n\x08\x44ownload\x12\x1b.filemanagement.FileRequest\x1a\x18.filemanagement.FileInfo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_management_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEINFO']._serialized_start=41
  _globals['_FILEINFO']._serialized_end=69
  _globals['_FILEREQUEST']._serialized_start=71
  _globals['_FILEREQUEST']._serialized_end=102
  _globals['_FILERESPONSE']._serialized_start=104
  _globals['_FILERESPONSE']._serialized_end=152
  _globals['_FILEMANAGER']._serialized_start=155
  _globals['_FILEMANAGER']._serialized_end=305
# @@protoc_insertion_point(module_scope)
